name: deploy_pages

# Only run this when the main branch changes
on:
  schedule:
      - cron: '30 6 */2 * *'
  push:
    branches:
    - main
  workflow_run:
    workflows: [nightly_build_mm]
    types:
      - completed
  workflow_dispatch:

# This job installs dependencies, build the site, and pushes it to `gh-pages``
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    # Install python
    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: 3.9
    
    - name: Install python dependencies
      run: |
        python -m pip install -U pip
        python -m pip install -r ./scripts/requirements.txt
    # Build the site
    - name: Build the site
      run: |
        python ./scripts/build.py
    # Push the book's HTML to github-pages
    - name: GitHub Pages action
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./_build/
        keep_files: true
