name: nightly_build_mm

on:
  workflow_run:
    workflows: [nightly_build_sr]
    types:
      - completed
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Cache pip
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - name: Cache PlatformIO
      uses: actions/cache@v3
      with:
        path: ~/.platformio
        key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }}

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.9

    - name: Install PlatformIO
      run: |
        python -m pip install --upgrade pip
        pip install --upgrade platformio
        wget https://github.com/MoonModules/WLED/archive/refs/heads/mdev.zip -O /tmp/mm.zip
        unzip /tmp/mm.zip -d /tmp
    - name: Run PlatformIO
      run: |
        cd /tmp/WLED-mdev
        pio run -e esp32_4MB_M || pio run -e esp32_4MB_M || true
        pio run -e esp32_4MB_S || pio run -e esp32_4MB_S || true
        pio run -e esp32_4MB_XL || pio run -e esp32_4MB_XL || true
        pio run -e esp32_4MB_M_debug || pio run -e esp32_4MB_M_debug || true
        pio run -e esp32_4MB_V4_S || pio run -e esp32_4MB_V4_S || true
        pio run -e esp32_4MB_V4_M || pio run -e esp32_4MB_V4_M || true
      env:
        PLATFORMIO_CI_SRC: /tmp/WLED-mdev
    - name: Copy Files
      run: |
        cd $GITHUB_WORKSPACE
        git rm -r $GITHUB_WORKSPACE/bin_dir/3_MoonMod_version/Nightly_build/*.bin || true
        cp $(find /tmp/WLED-mdev/build_output/release -name *.bin) $GITHUB_WORKSPACE/bin_dir/3_MoonMod_version/Nightly_build/
        date -I | tr -d '\n' >$GITHUB_WORKSPACE/bin_dir/3_MoonMod_version/Nightly_build/lastupdate.txt
        echo -n ", version: " >>$GITHUB_WORKSPACE/bin_dir/3_MoonMod_version/Nightly_build/lastupdate.txt
        versionvalue=($(jq -r '.version' /tmp/WLED-mdev/package.json))
        echo -n "$versionvalue" >>$GITHUB_WORKSPACE/bin_dir/3_MoonMod_version/Nightly_build/lastupdate.txt
    - name: Commit Files
      run: |
        cd $GITHUB_WORKSPACE
        git config user.name "GitHub Actions Bot"
        git config user.email "<>"
        git add $GITHUB_WORKSPACE/bin_dir/3_MoonMod_version/Nightly_build/*.bin
        git add $GITHUB_WORKSPACE/bin_dir/3_MoonMod_version/Nightly_build/lastupdate.txt
        git commit -m "Commit MoonMod Nightly Build"
        git push origin main
